version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo

  api:
    build: ./backend
    depends_on: [db]
    environment:
      DB_DSN: postgres://todo:todo@db:5432/todo?sslmode=disable
      JWT_SECRET: devsecret
    ports: ["8080:8080"]

  web:
    build: ./frontend
    depends_on: [api]

    ports:
      - "5173:80"
      - "80:80"
