version: "3.9"
services:
  api:
    build: ./backend
    ports: [ "8080:8080" ]
    environment:
      DB_DSN: postgres://todo:todo@db:5432/todo?sslmode=disable
      JWT_SECRET: devsecret
    depends_on: [ db ]
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    volumes: [ dbdata:/var/lib/postgresql/data ]
  web:
    build: ./frontend
    ports: [ "5173:80" ]
volumes:
  dbdata:
